import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

import { buildSettlementDocumentSummary } from "@/features/settlements/settlement-document-summary";

type Row = Record<string, unknown>;
type Props = { detail: Row; services: Row[]; bonuses: Row[]; productLines?: Row[]; deductions: Row[]; payments?: Row[] };
const money = (value: unknown) => `S/ ${Number(value ?? 0).toFixed(2)}`;
const relation = (value: unknown, key: string) => { const item = Array.isArray(value) ? value[0] : value; return item && typeof item === "object" ? String((item as Row)[key] ?? "") : ""; };
const dateTime = (value: unknown) => value ? new Intl.DateTimeFormat("es-PE", { timeZone: "America/Lima", dateStyle: "short", timeStyle: "short", hour12: false }).format(new Date(String(value))) : "—";
const styles = StyleSheet.create({ page: { padding: 36, fontSize: 9, color: "#0f172a", fontFamily: "Helvetica" }, title: { fontSize: 17, fontFamily: "Helvetica-Bold" }, subtitle: { color: "#475569", marginBottom: 12 }, section: { marginTop: 12 }, heading: { fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 5 }, grid: { flexDirection: "row", flexWrap: "wrap" }, field: { width: "50%", paddingVertical: 2 }, box: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 4, padding: 8 }, columns: { flexDirection: "row", gap: 8 }, column: { width: "50%", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 4, padding: 8 }, row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 }, strong: { fontFamily: "Helvetica-Bold" }, muted: { color: "#64748b" }, footer: { position: "absolute", bottom: 24, left: 36, right: 36, textAlign: "center", color: "#64748b", fontSize: 8 } });

export function EmployeeSettlementPdf({ detail, services, bonuses, productLines = [], deductions, payments = [] }: Props) {
  void bonuses;
  const summary = buildSettlementDocumentSummary(detail, services, deductions, productLines);
  const paid = detail.status === "paid"; const activePayments = payments.filter((payment) => ["posted", "active"].includes(String(payment.status ?? "posted")));
  return <Document title={`Liquidación ${String(detail.settlement_number ?? "")}`} author="La Bajadita Barber Studio"><Page size="A4" style={styles.page}>
    <Text style={styles.title}>LA BAJADITA BARBER STUDIO</Text><Text style={styles.subtitle}>Liquidación / Comprobante de pago</Text>
    <View style={styles.grid}>{[["Número", detail.settlement_number], ["Estado", paid ? "Pagada" : detail.status], ["Empleado", relation(detail.employee, "full_name")], ["Documento", relation(detail.employee, "document_number")], ["Sede", relation(detail.branch, "name")], ["Periodo", `${relation(detail.period, "start_date")} al ${relation(detail.period, "end_date")}`]].map(([label, value]) => <View key={String(label)} style={styles.field}><Text>{String(label)}: <Text style={styles.strong}>{String(value ?? "—")}</Text></Text></View>)}</View>
    <View style={styles.section}><Text style={styles.heading}>RESUMEN DE PRODUCCIÓN</Text><View style={[styles.box, styles.grid]}>{[["Producción reconocida", summary.totalProduction], ["Aporte operativo", summary.productionContribution], ["Base comisionable", summary.productionBase], ["Comisión", summary.commissionRate.toFixed(2) + "%"]].map(([label, value]) => <View key={String(label)} style={styles.field}><Text>{String(label)}: <Text style={styles.strong}>{typeof value === "number" ? money(value) : String(value)}</Text></Text></View>)}</View></View>
    <View style={[styles.section, styles.columns]}><View style={styles.column}><Text style={styles.heading}>INGRESOS</Text>{summary.incomes.map((line) => <View key={line.id} style={styles.row}><Text>{line.label}</Text><Text>{money(line.amount)}</Text></View>)}</View><View style={styles.column}><Text style={styles.heading}>EGRESOS</Text>{summary.expenses.map((line) => <View key={line.id} style={styles.row}><Text>{line.label}</Text><Text>-{money(line.amount)}</Text></View>)}</View></View>
    <View style={[styles.section, styles.box]}><Text style={styles.strong}>NETO FINAL: {money(detail.net_pay_amount)}</Text></View>
    <View style={styles.section}><Text style={styles.heading}>DETALLE DE PAGOS</Text>{activePayments.length ? <>{activePayments.map((payment) => <View key={String(payment.id)} style={styles.row}><Text>{relation(payment.payment_method, "name")}{payment.reference ? ` · ${String(payment.reference)}` : ""}</Text><Text>{money(payment.amount)}</Text></View>)}<View style={styles.row}><Text style={styles.strong}>Total pagado</Text><Text style={styles.strong}>{money(activePayments.reduce((sum, payment) => sum + Number(payment.amount ?? 0), 0))}</Text></View></> : <Text>{relation(detail.payment_method, "name") || "Pendiente"}</Text>}</View>
    <View style={styles.section}><Text style={styles.heading}>TRAZABILIDAD</Text><Text>Confirmó: {relation(detail.reviewed, "full_name") || "Pendiente"} · Aprobó: {relation(detail.approved, "full_name") || "Pendiente"} · Pagó: {relation(detail.paid, "full_name") || "Pendiente"}</Text>{paid ? <Text>Fecha: {dateTime(detail.paid_at)}</Text> : null}</View>
    <Text style={styles.footer}>No es documento tributario</Text>
  </Page></Document>;
}
