"use client";

import { Button } from "@/components/ui/button";
import { formatMoney } from "@/features/pos/pos-utils";
import { getSettlementStatusLabel } from "@/features/settlements/settlement-status";

type Props = { detail: Record<string, unknown>; services: Array<Record<string, unknown>>; bonuses: Array<Record<string, unknown>>; deductions: Array<Record<string, unknown>>; onClose: () => void };
const relation = (value: unknown, key: string) => { const item = Array.isArray(value) ? value[0] : value; return item && typeof item === "object" ? String((item as Record<string, unknown>)[key] ?? "") : ""; };

export function EmployeeSettlementDocument({ detail, services, bonuses, deductions, onClose }: Props) {
  return <div className="settlement-print-area space-y-5 bg-white text-slate-900">
    <div className="no-print flex justify-end gap-2"><Button type="button" className="bg-slate-100 text-slate-700 hover:bg-slate-200" onClick={onClose}>Cerrar</Button><Button type="button" onClick={() => window.print()}>Imprimir</Button></div>
    <header className="border-b-2 border-slate-900 pb-4"><p className="text-xl font-bold">La Bajadita Barber Studio</p><p className="mt-1 text-sm">Liquidacion operativa de empleado · No es documento tributario</p></header>
    <section className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm"><p>Numero: <strong>{String(detail.settlement_number ?? "")}</strong></p><p>Estado: <strong>{getSettlementStatusLabel(String(detail.status ?? ""))}</strong></p><p>Empleado: <strong>{relation(detail.employee,"full_name")}</strong></p><p>Documento: <strong>{relation(detail.employee,"document_number") || "Sin registro"}</strong></p><p>Cargo: <strong>{relation(detail.employee,"position") || "Sin registro"}</strong></p><p>Sede: <strong>{relation(detail.branch,"name")}</strong></p><p>Periodo: <strong>{relation(detail.period,"start_date")} al {relation(detail.period,"end_date")}</strong></p><p>Porcentaje: <strong>{Number(detail.commission_rate ?? 0).toFixed(2)} %</strong></p></section>
    <section><p className="font-semibold">Detalle de servicios</p><table className="mt-2 w-full text-xs"><thead><tr className="border-b text-left"><th className="py-2">Fecha</th><th>Servicio</th><th className="text-right">Base</th><th className="text-right">%</th><th className="text-right">Comision</th><th className="text-right">Fija</th></tr></thead><tbody>{services.map((line) => <tr key={String(line.id)} className="border-b border-slate-100"><td className="py-2">{new Date(String(line.production_date_snapshot)).toLocaleDateString("es-PE")}</td><td>{String(line.service_name_snapshot)}</td><td className="text-right">{formatMoney(Number(line.commissionable_amount))}</td><td className="text-right">{Number(line.commission_rate).toFixed(2)}</td><td className="text-right">{formatMoney(Number(line.commission_amount))}</td><td className="text-right">{formatMoney(Number(line.fixed_commission_amount))}</td></tr>)}</tbody></table></section>
    <section className="grid grid-cols-2 gap-6 text-sm"><div className="space-y-1"><p>Comision porcentual: <strong>{formatMoney(Number(detail.percentage_commission_total))}</strong></p><p>Comisiones reward: <strong>{formatMoney(Number(detail.reward_fixed_commission_total))}</strong></p><p>Comisiones cortesia: <strong>{formatMoney(Number(detail.courtesy_fixed_commission_total))}</strong></p><p>Bonos productos: <strong>{formatMoney(Number(detail.product_bonus_total))}</strong> ({bonuses.length})</p></div><div className="space-y-1"><p>Ingresos brutos: <strong>{formatMoney(Number(detail.gross_pay_amount))}</strong></p><p>Deducciones previas: <strong>{formatMoney(Number(detail.debt_deduction_total))}</strong> ({deductions.length})</p><p>Neto previo al descuento: <strong>{formatMoney(Number(detail.net_before_mandatory_discount ?? 0))}</strong></p><p>Descuento obligatorio ({Number(detail.mandatory_discount_rate ?? 0).toFixed(2)} %): <strong>-{formatMoney(Number(detail.mandatory_discount_amount ?? 0))}</strong></p><p className="text-lg">Neto final a pagar: <strong>{formatMoney(Number(detail.net_pay_amount))}</strong></p></div></section>
    <section className="border-t pt-3 text-sm"><p>Metodo de pago: <strong>{relation(detail.payment_method,"name") || "Pendiente"}</strong></p><p>Referencia: <strong>{String(detail.payment_reference ?? "Sin referencia")}</strong></p><p>Observaciones: {String(detail.notes ?? "Sin observaciones")}</p><p className="mt-2">Reviso: {relation(detail.reviewed,"full_name") || "Pendiente"} · Aprobo: {relation(detail.approved,"full_name") || "Pendiente"} · Pago: {relation(detail.paid,"full_name") || "Pendiente"}</p></section>
  </div>;
}
