"use client";

import { useEffect, useMemo, useState } from "react";

import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { formatMoney } from "@/features/pos/pos-utils";

type Employee = { id: string; full_name: string };
type Mode = "general" | "masiva" | "individual";

export function PaymentSimulationsPageClient() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [mode, setMode] = useState<Mode>("general"); const [employeeId, setEmployeeId] = useState(""); const [gross, setGross] = useState(""); const [debts, setDebts] = useState(""); const [rate, setRate] = useState("1");
  useEffect(() => { void fetch("/api/admin/payment-simulations", { cache: "no-store" }).then((response) => response.json()).then((payload) => setEmployees(payload.data ?? [])).catch(() => setEmployees([])); }, []);
  const result = useMemo(() => { const before = Math.max(0, Number(gross) - Number(debts)); const discount = before * Math.max(0, Number(rate)) / 100; return { before, discount, net: Math.max(0, before - discount) }; }, [gross, debts, rate]);
  return <div className="space-y-4"><section className="rounded-2xl border border-sky-100 bg-sky-50/60 p-5"><p className="text-sm font-semibold text-slate-900">Simulaciones de pago</p><p className="mt-1 text-sm text-slate-600">Herramienta de consulta. No crea liquidaciones ni modifica deudas.</p></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-4"><Select value={mode} onChange={(event) => setMode(event.target.value as Mode)}><option value="general">General</option><option value="masiva">Masiva</option><option value="individual">Individual</option></Select>{mode === "individual" ? <Select value={employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">Seleccionar empleado</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}</option>)}</Select> : <div className="hidden md:block" />}<Input type="number" min="0" step="0.01" value={gross} onChange={(event) => setGross(event.target.value)} placeholder="Ingresos brutos" /><Input type="number" min="0" step="0.01" value={debts} onChange={(event) => setDebts(event.target.value)} placeholder="Deducciones previas" /><Input type="number" min="0" step="0.01" value={rate} onChange={(event) => setRate(event.target.value)} placeholder="Descuento obligatorio %" /></div>{mode === "individual" && !employeeId ? <p className="mt-3 text-xs text-amber-700">Selecciona un empleado para identificar la simulacion. Los valores se ingresan manualmente.</p> : null}</section><section className="grid gap-3 md:grid-cols-3"><article className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">Neto antes del descuento</p><p className="mt-1 text-lg font-semibold">{formatMoney(result.before)}</p></article><article className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs text-amber-700">Descuento obligatorio ({Number(rate || 0).toFixed(2)} %)</p><p className="mt-1 text-lg font-semibold text-amber-800">-{formatMoney(result.discount)}</p></article><article className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs text-emerald-700">Neto estimado</p><p className="mt-1 text-lg font-bold text-emerald-800">{formatMoney(result.net)}</p></article></section></div>;
}
