"use client";

import { useEffect, useState } from "react";
import Swal from "sweetalert2";
import { Button } from "@/components/ui/button";
import { buildWhatsAppUrl, renderWhatsAppTemplate } from "@/lib/whatsapp/template";

type ContactRow = { id:string; customerId:string; branchId:string; customerName:string; phone:string; branchName:string; barberName:string; serviceName?:string; time?:string; services?:string[]; status?:string; address?:string };
type Template = { id:string; contact_type:string; body:string };
type Payload = { reminders:ContactRow[]; thanks:ContactRow[]; templates:Template[]; today:string };

export function ContactsPageClient() {
  const [payload,setPayload]=useState<Payload|null>(null); const [tab,setTab]=useState<"reminders"|"thanks">("reminders"); const [busy,setBusy]=useState<string|null>(null);
  async function load(){try{const response=await fetch("/api/admin/contacts",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error);setPayload(result);}catch(error){const message=error instanceof Error?error.message:"No se pudieron cargar los contactos.";console.error("[contacts/ui] Error al cargar",{message});await Swal.fire({icon:"error",title:"No se pudieron cargar los contactos",text:message,confirmButtonColor:"#0f766e"});}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  async function open(row:ContactRow,type:"reservation_reminder"|"post_service_thanks",marked=false){if(!payload)return;const template=payload.templates.find((item)=>item.contact_type===type);if(!template){await Swal.fire({icon:"info",title:"Plantilla no disponible",text:"Configura una plantilla activa antes de continuar.",confirmButtonColor:"#0f766e"});return;}const message=renderWhatsAppTemplate(template.body,{cliente:row.customerName,fecha:payload.today,hora:row.time??"",sede:row.branchName,direccion:row.address??"",barbero:row.barberName,servicio:row.serviceName??"No especificado",servicios:(row.services??[]).join(", ")||"No especificado",telefono_sede:""});setBusy(row.id);try{window.open(buildWhatsAppUrl(row.phone,message),"_blank","noopener,noreferrer");await fetch("/api/admin/contacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:row.customerId,branchId:row.branchId,reservationId:type==="reservation_reminder"?row.id:null,saleId:type==="post_service_thanks"?row.id:null,contactType:type,templateId:template.id,phone:row.phone,message,status:marked?"marked_sent":"opened"})});}catch(error){console.error("[contacts/ui] Error al registrar contacto",{message:error instanceof Error?error.message:"Error inesperado"});}finally{setBusy(null);}}
  const rows=tab==="reminders"?payload?.reminders??[]:payload?.thanks??[];
  return <div className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-2"><Button type="button" className={tab==="reminders"?"":"bg-slate-100 text-slate-700 hover:bg-slate-200"} onClick={()=>setTab("reminders")}>Recordatorios de hoy</Button><Button type="button" className={tab==="thanks"?"":"bg-slate-100 text-slate-700 hover:bg-slate-200"} onClick={()=>setTab("thanks")}>Agradecimientos de hoy</Button></div></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="divide-y divide-slate-100">{rows.length?rows.map((row)=><article key={row.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-900">{row.customerName}</p><p className="text-sm text-slate-600">{row.phone} - {row.branchName} {row.time?`- ${row.time}`:""}</p><p className="text-xs text-slate-500">{row.barberName} - {row.serviceName??(row.services??[]).join(", ")}</p></div><div className="flex gap-2"><Button type="button" disabled={busy===row.id} onClick={()=>void open(row,tab==="reminders"?"reservation_reminder":"post_service_thanks")}>WhatsApp</Button><Button type="button" className="bg-slate-100 text-slate-700 hover:bg-slate-200" disabled={busy===row.id} onClick={()=>void open(row,tab==="reminders"?"reservation_reminder":"post_service_thanks",true)}>Marcar enviado</Button></div></article>):<p className="p-8 text-center text-sm text-slate-500">No hay contactos pendientes para hoy.</p>}</div></section></div>;
}
