"use client";

import { useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { formatMoney } from "@/features/pos/pos-utils";

type Branch = { id: string; name: string };
type Analysis = Record<string, unknown>;
const today = new Date().toLocaleDateString("en-CA", { timeZone: "America/Lima" });
const monthStart = `${today.slice(0, 8)}01`;
const amount = (value: unknown) => Number(value ?? 0);
const read = (object: unknown, key: string) => amount((object as Record<string, unknown> | null)?.[key]);

function Line({ label, value, emphasis = false }: { label: string; value: number; emphasis?: boolean }) {
  return <div className={`flex items-center justify-between gap-4 py-2 text-sm ${emphasis ? "border-t border-slate-200 font-bold text-slate-950" : "text-slate-700"}`}><span>{label}</span><span>{formatMoney(value)}</span></div>;
}

export function ProfitLossPageClient() {
  const [from, setFrom] = useState(monthStart); const [to, setTo] = useState(today); const [branchId, setBranchId] = useState("");
  const [branches, setBranches] = useState<Branch[]>([]); const [data, setData] = useState<Analysis | null>(null); const [loading, setLoading] = useState(true);
  const query = useMemo(() => new URLSearchParams({ from, to, ...(branchId ? { branchId } : {}) }).toString(), [from, to, branchId]);
  useEffect(() => { const controller = new AbortController(); void fetch("/api/admin/branches", { cache: "no-store", signal: controller.signal }).then(async (r) => { const p = await r.json(); if (!r.ok) throw new Error(p.error ?? "No se pudieron cargar las sedes."); setBranches(p.data ?? []); }).catch((error: unknown) => { if ((error as Error).name !== "AbortError") console.error("[profit-loss/ui] No se pudieron cargar las sedes", { message: error instanceof Error ? error.message : "Error inesperado" }); }); return () => controller.abort(); }, []);
  useEffect(() => { const controller = new AbortController(); void Promise.resolve().then(() => { if (!controller.signal.aborted) setLoading(true); }); void fetch(`/api/admin/finance/analysis-v2?${query}`, { cache: "no-store", signal: controller.signal }).then(async (r) => { const payload = await r.json(); if (!r.ok) throw new Error(payload.error); setData(payload.data ?? null); }).catch((error: unknown) => { if ((error as Error).name !== "AbortError") void Swal.fire({ icon: "error", title: "No se pudo cargar Ganancias y Pérdidas", text: error instanceof Error ? error.message : "Error inesperado", confirmButtonColor: "#0f766e" }); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [query]);
  const sales = (data?.sales ?? {}) as Record<string, unknown>; const costs = (data?.directCosts ?? {}) as Record<string, unknown>; const expenses = (data?.expenses ?? {}) as Record<string, unknown>; const personnel = (data?.personnel ?? {}) as Record<string, unknown>; const profit = (data?.profit ?? {}) as Record<string, unknown>;
  const service = read(sales, "serviceSales"); const barberProducts = read(sales, "barbershopProductSales"); const cafeteria = read(sales, "cafeteriaProductSales"); const other = Math.max(read(sales, "netCommercialSales") - service - barberProducts - cafeteria, 0); const income = read(sales, "netCommercialSales"); const productCosts = read(costs, "productCogs"); const courtesyCost = read(costs, "courtesyProductRealCost"); const personnelCost = read(personnel, "recognizedPersonnelCost") || read(personnel, "accruedCost"); const directCosts = productCosts + courtesyCost + personnelCost; const operatingExpenses = read(expenses, "operatingExpenses"); const grossMargin = income - directCosts; const operatingResult = read(profit, "operatingProfit") || grossMargin - operatingExpenses;
  return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Desde<Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="text-sm">Hasta<Input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><label className="min-w-52 text-sm">Sede<Select value={branchId} onChange={(e) => setBranchId(e.target.value)}><option value="">Todas las sedes</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></label><Button type="button" onClick={() => setData(null)}>Actualizar</Button></div></section><section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">Ganancias y Pérdidas</h2><p className="mt-1 text-sm text-slate-500">Asientos financieros canónicos del {from} al {to}.</p>{loading ? <p className="py-12 text-center text-sm text-slate-500">Calculando resultado...</p> : <div className="mt-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Ventas / ingresos</p><Line label="Servicios" value={service} /><Line label="Productos barbería" value={barberProducts} /><Line label="Productos cafetería" value={cafeteria} /><Line label="Otros ingresos" value={other} /><Line label="Ingresos totales" value={income} emphasis /><p className="mt-5 text-xs font-bold uppercase tracking-wide text-rose-700">Costos directos</p><Line label="Costo productos barbería y cafetería vendidos" value={productCosts} /><Line label="Costo real de cortesías" value={courtesyCost} /><Line label="Costo de personal devengado" value={personnelCost} /><Line label="Total costos directos" value={directCosts} emphasis /><Line label="Margen / utilidad bruta" value={grossMargin} emphasis /><p className="mt-5 text-xs font-bold uppercase tracking-wide text-amber-700">Gastos operativos</p><Line label="Gastos operativos" value={operatingExpenses} /><Line label="Resultado operativo" value={operatingResult} emphasis /></div>}</article><article className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-sm"><p className="text-sm text-slate-300">Resultado operativo</p><p className={`mt-2 text-4xl font-bold ${operatingResult >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{formatMoney(operatingResult)}</p><p className="mt-3 text-sm text-slate-300">Margen operativo: {income > 0 ? `${((operatingResult / income) * 100).toFixed(2)} %` : "—"}</p><div className="mt-8 rounded-xl bg-white/10 p-4 text-sm text-slate-200">El costo de personal es devengado: incluye remuneraciones reconocidas, incluso si la liquidación aún no fue pagada. Esto evita mezclar caja con rentabilidad.</div></article></section></div>;
}
