"use client";

import { type ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { formatMoney } from "@/features/pos/pos-utils";

type Branch = { id: string; name: string };
type Session = { id: string; branch_id: string; status: "open" | "closed"; opened_at: string; branch: { name?: string } | Array<{ name?: string }> | null };
type Payment = { sale_id: string; created_at: string; sale_total: number | string; customer_name: string; barber_name: string; amount: number | string; change_amount: number | string; payment_method_name: string; payment_kind: string };
type Barber = { employee_id: string; employee_name: string; services_count: number | string; service_gross: number | string; operational_contribution: number | string; commissionable_base: number | string };
type Category = { name: string; item_type: "service" | "product"; total: number | string };
type RecentSale = { id: string; created_at: string; total: number | string; paid_total: number | string; courtesy_total: number | string; discount_total: number | string; operation_kind: string; customer_name: string; barber_name: string; payment_methods: string[] };
type Breakdown = { summary?: Record<string, number | string>; payments?: Payment[]; barbers?: Barber[]; categories?: Category[]; adjustments?: Record<string, number | string>; recent_sales?: RecentSale[] };
type Payload = { date: string; branchId: string; branches: Branch[]; sessions: Session[]; data: Breakdown };

const toNumber = (value: unknown) => Number(value ?? 0);
const time = (value: string) => new Intl.DateTimeFormat("es-PE", { timeZone: "America/Lima", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const sessionName = (session: Session) => {
  const branch = Array.isArray(session.branch) ? session.branch[0] : session.branch;
  return `${branch?.name ?? "Sede"} · ${session.status === "open" ? "Activa" : "Cerrada"} · ${time(session.opened_at)}`;
};

export function SalesControlPageClient() {
  const [payload, setPayload] = useState<Payload | null>(null);
  const [date, setDate] = useState("");
  const [branchId, setBranchId] = useState("");
  const [sessionId, setSessionId] = useState("");
  const [tab, setTab] = useState<"payments" | "barbers" | "categories" | "adjustments" | "recent">("payments");
  const [loading, setLoading] = useState(true);
  const [commissionByBarber, setCommissionByBarber] = useState<Record<string, string>>({});

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const query = new URLSearchParams(); if (date) query.set("date", date); if (branchId) query.set("branchId", branchId); if (sessionId) query.set("posSessionId", sessionId);
      const response = await fetch(`/api/admin/sales-control?${query}`, { cache: "no-store" }); const body = await response.json();
      if (!response.ok) throw new Error(body.error || "No se pudo cargar el control de ventas.");
      setPayload(body); setDate((current) => current || body.date); setBranchId(body.branchId ?? "");
    } catch (error) { await Swal.fire({ icon: "error", title: "No se pudo cargar el control", text: error instanceof Error ? error.message : "Error inesperado" }); }
    finally { setLoading(false); }
  }, [date, branchId, sessionId]);
  useEffect(() => { void load(); }, [load]);

  const summary = payload?.data.summary ?? {};
  const payments = payload?.data.payments ?? [];
  const groupedPayments = useMemo(() => payments.reduce<Record<string, Payment[]>>((groups, payment) => { const key = payment.payment_method_name || "Sin método"; (groups[key] ??= []).push(payment); return groups; }, {}), [payments]);
  const visibleSessions = (payload?.sessions ?? []).filter((session) => !branchId || session.branch_id === branchId);
  const maxCategory = Math.max(...(payload?.data.categories ?? []).map((item) => toNumber(item.total)), 1);

  return <section className="space-y-5">
    <header><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Supervisión operativa</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Control de ventas</h1><p className="mt-1 text-sm text-slate-600">Corte por fecha operativa de Lima. Incluye ventas completadas del POS, incluso si una sesión permanece abierta.</p></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><label className="text-sm font-medium">Fecha operativa<Input type="date" value={date} onChange={(event) => { setDate(event.target.value); setSessionId(""); }} /></label><label className="text-sm font-medium">Sede<Select value={branchId} onChange={(event) => { setBranchId(event.target.value); setSessionId(""); }}><option value="">Todas las sedes permitidas</option>{payload?.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></label><label className="text-sm font-medium">Sesión POS<Select value={sessionId} onChange={(event) => setSessionId(event.target.value)}><option value="">Todas las ventas del día</option>{visibleSessions.map((session) => <option key={session.id} value={session.id}>{sessionName(session)}</option>)}</Select></label><Button className="self-end" disabled={loading} onClick={() => void load()}>Actualizar</Button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Ventas completadas" value={String(toNumber(summary.sales_count))} /><Metric label="Facturación neta" value={formatMoney(toNumber(summary.net_total))} /><Metric label="Cobro real" value={formatMoney(toNumber(summary.real_collected_total))} hint="Excluye crédito interno" /><Metric label="Aportes de producción" value={formatMoney(toNumber(summary.operational_contribution_total))} /><Metric label="Base comisionable" value={formatMoney(toNumber(summary.commissionable_base_total))} /></section>
    <nav className="flex flex-wrap gap-2 border-b border-slate-200">{(["payments", "barbers", "categories", "adjustments", "recent"] as const).map((value) => <button key={value} onClick={() => setTab(value)} className={`px-3 py-2 text-sm font-semibold ${tab === value ? "border-b-2 border-emerald-600 text-emerald-700" : "text-slate-500"}`}>{({ payments: "Cobros por método", barbers: "Ranking de barberos", categories: "Ventas por categoría", adjustments: "Descuentos y operaciones", recent: "Últimas ventas" })[value]}</button>)}</nav>
    {loading ? <section className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-500">Cargando control de ventas…</section> : null}
    {!loading && tab === "payments" ? <section className="space-y-4">{Object.entries(groupedPayments).length === 0 ? <Empty /> : Object.entries(groupedPayments).map(([method, rows]) => <article key={method} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><h2 className="font-semibold">{method}</h2><p className="text-xs text-slate-500">{rows.length} cobro(s) · cada fila representa una venta o parte de una venta mixta.</p></div><strong className="text-emerald-700">{formatMoney(rows.reduce((sum, row) => sum + toNumber(row.amount), 0))}</strong></header><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Hora</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Barbero</th><th className="px-4 py-3">Total venta</th><th className="px-4 py-3">Cobrado aquí</th><th className="px-4 py-3">Vuelto</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.sale_id}-${method}-${index}`} className="border-t border-slate-100"><td className="px-4 py-3">{time(row.created_at)}</td><td className="px-4 py-3">{row.customer_name}</td><td className="px-4 py-3">{row.barber_name}</td><td className="px-4 py-3">{formatMoney(toNumber(row.sale_total))}</td><td className="px-4 py-3 font-semibold text-emerald-700">{formatMoney(toNumber(row.amount))}</td><td className="px-4 py-3">{formatMoney(toNumber(row.change_amount))}</td></tr>)}</tbody></table></div></article>)}</section> : null}
    {!loading && tab === "barbers" ? <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 px-4 py-3"><h2 className="font-semibold">Ranking de barberos</h2><p className="text-sm text-slate-500">El porcentaje inicia en 50% y permite simular el pago sobre la base comisionable. No guarda ni liquida pagos.</p></header><Table headers={["#", "Barbero", "Servicios", "Bruto servicios", "Aportes", "Base comisionable", "% comisión", "Pago estimado"]}>{(payload?.data.barbers ?? []).map((barber, index) => { const percentage = commissionByBarber[barber.employee_id] ?? "50"; const estimatedPayment = toNumber(barber.commissionable_base) * Math.min(Math.max(toNumber(percentage), 0), 100) / 100; return <tr key={barber.employee_id} className="border-t border-slate-100"><td className="px-4 py-3 font-bold text-slate-500">{index + 1}</td><td className="px-4 py-3 font-semibold">{barber.employee_name}</td><td className="px-4 py-3">{barber.services_count}</td><td className="px-4 py-3">{formatMoney(toNumber(barber.service_gross))}</td><td className="px-4 py-3 text-amber-700">-{formatMoney(toNumber(barber.operational_contribution))}</td><td className="px-4 py-3 font-bold text-emerald-700">{formatMoney(toNumber(barber.commissionable_base))}</td><td className="px-4 py-3"><div className="relative w-24"><Input aria-label={`Porcentaje de comisión de ${barber.employee_name}`} className="h-9 pr-7" type="number" min="0" max="100" step="0.01" value={percentage} onChange={(event) => setCommissionByBarber((current) => ({ ...current, [barber.employee_id]: event.target.value }))} /><span className="pointer-events-none absolute right-2 top-2 text-xs text-slate-500">%</span></div></td><td className="px-4 py-3 font-bold text-emerald-700">{formatMoney(estimatedPayment)}</td></tr>; })}</Table>{(payload?.data.barbers ?? []).length === 0 ? <Empty /> : null}</section> : null}
    {!loading && tab === "categories" ? <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Ventas por categoría</h2><p className="mt-1 text-sm text-slate-500">Servicios se mantienen separados; los demás ítems usan su categoría de producto.</p><div className="mt-5 space-y-4">{(payload?.data.categories ?? []).map((category) => <div key={`${category.item_type}-${category.name}`}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="font-medium">{category.name}</span><strong>{formatMoney(toNumber(category.total))}</strong></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.max((toNumber(category.total) / maxCategory) * 100, 2)}%` }} /></div></div>)}{(payload?.data.categories ?? []).length === 0 ? <Empty /> : null}</div></section> : null}
    {!loading && tab === "adjustments" ? <section className="grid gap-4 md:grid-cols-2"><Adjustment label="Cortesías entregadas" value={toNumber(payload?.data.adjustments?.courtesy_total)} tone="amber" /><Adjustment label="Descuentos comerciales" value={toNumber(payload?.data.adjustments?.commercial_discount_total)} tone="rose" /><Adjustment label="Descuentos por Rewards" value={toNumber(payload?.data.adjustments?.reward_discount_total)} tone="violet" /><Adjustment label="Ventas a crédito de empleado" value={toNumber(payload?.data.adjustments?.internal_credit_total)} tone="slate" /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:col-span-2"><h2 className="font-semibold">Operaciones internas</h2><p className="mt-1 text-sm text-slate-500">No se consideran cobro real de caja; se conservan como venta/deuda auditada.</p><strong className="mt-3 block text-3xl text-slate-900">{toNumber(payload?.data.adjustments?.internal_operations)}</strong><span className="text-sm text-slate-500">operación(es) interna(s)</span></section></section> : null}
    {!loading && tab === "recent" ? <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><Table headers={["Hora", "Cliente", "Barbero", "Métodos", "Descuento/cortesía", "Total"]}>{(payload?.data.recent_sales ?? []).map((sale) => <tr key={sale.id} className="border-t border-slate-100"><td className="px-4 py-3">{time(sale.created_at)}</td><td className="px-4 py-3">{sale.customer_name}</td><td className="px-4 py-3">{sale.barber_name}</td><td className="px-4 py-3">{sale.payment_methods.join(", ") || "Sin pago"}</td><td className="px-4 py-3 text-slate-600">{sale.courtesy_total ? `Cortesía ${formatMoney(toNumber(sale.courtesy_total))}` : sale.discount_total ? `Descuento ${formatMoney(toNumber(sale.discount_total))}` : "—"}</td><td className="px-4 py-3 font-bold text-emerald-700">{formatMoney(toNumber(sale.total))}</td></tr>)}</Table>{(payload?.data.recent_sales ?? []).length === 0 ? <Empty /> : null}</section> : null}
  </section>;
}

function Metric({ label, value, hint }: { label: string; value: string; hint?: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium text-slate-500">{label}</p><strong className="mt-1 block text-xl text-slate-950">{value}</strong>{hint ? <p className="mt-1 text-xs text-slate-400">{hint}</p> : null}</article>; }
function Empty() { return <p className="p-6 text-center text-sm text-slate-500">No hay ventas para los filtros seleccionados.</p>; }
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Adjustment({ label, value, tone }: { label: string; value: number; tone: "amber" | "rose" | "violet" | "slate" }) { const colors = { amber: "text-amber-700", rose: "text-rose-700", violet: "text-violet-700", slate: "text-slate-700" }; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><strong className={`mt-2 block text-2xl ${colors[tone]}`}>{formatMoney(value)}</strong></article>; }
